// react/chuck-norris/src/App.tsx
import React, {useEffect, useReducer} from 'react';
import logo from './logo.jpg';
import './App.css';

export interface Joke {
  value: {
    joke: string
  }
}

export const tidy = (text: string) =>
  text.replace(/&quot;/g, '"');

type State =
  | { status: 'empty' }
  | { status: 'loading' }
  | { status: 'success', jokeText: string }
  | { status: 'failure', error: string }

type Action =
  | { type: 'fetch' }
  | { type: 'success', result: string }
  | { type: 'failure', error: string };

const reducer = (state: State, action: Action): State => {
  switch (action.type) {
    case 'success':
      return {status: 'success', jokeText: action.result};
    case 'failure':
      return {status: 'failure', error: action.error};
    case 'fetch':
      return {status: 'loading'};
  }
};

function App() {
  const [jokeData, dispatch] = useReducer(reducer, {status: 'empty'});
  const fetchRandomJoke = async () => {
    dispatch({type: 'fetch'});
    await fetch('http://api.icndb.com/jokes/random')
      .then(response => response.json() as Promise<Joke>)
      .then(joke => joke.value.joke)
      .then(tidy)
      .then(joke => dispatch({type: 'success', result: joke}))
      .catch((e: Error) => dispatch({type: 'failure', error: e.message}));
  };

  useEffect(() => {
    fetchRandomJoke();
  }, []);

  const refreshJoke = async () => {
    await fetchRandomJoke();
  };

  return (
    <div className="App">
      <div className="container-fluid m-1">
        <header className="row">
          <figure className="figure">
            <img className="figure-caption" src={logo} alt="Chuck Norris Logo"/>
            <figcaption className="figure-caption">
              <a data-testid="attribution"
                 href="https://www.flickr.com/photos/enriquespics/2058486062">
                by Carlos Killpack
              </a>
            </figcaption>
          </figure>
        </header>
        <main className="row">
          {jokeData.status === 'success' &&
          <p data-testid="joke-text">Random Wisdom: {jokeData.jokeText}.</p>
          }
          {jokeData.status === 'failure' &&
          <p className="alert alert-danger" data-testid="error">{jokeData.error}</p>
          }
          {jokeData.status === 'loading' &&
          <div className="spinner-border" role="status">
              <span className="sr-only">Loading...</span>
          </div>
          }
        </main>
        <footer className="row">
          <button className="btn btn-primary"
                  onClick={refreshJoke}
                  disabled={jokeData.status === 'loading'}>
            Refresh
          </button>
        </footer>
      </div>
    </div>
  );
}

export default App;

// svelte/chuck-norris/src/App.svelte
<script lang="ts">
  interface JokeText {
    value: string
  }

  const fetchRandomJoke = (): Promise<string> => fetch('https://api.chucknorris.io/jokes/random')
    .then(res => res.json() as JokeText)
    .then(joke => joke.value);

  let fetchJoke$ = fetchRandomJoke();
</script>

<header>
  <h1>Chuck Norris</h1>
</header>
<main>
  <figure>
    <img src="chuck-norris-logo.png" alt="Chuck Norris approves!">
    <figcaption>Chuck Norris approves!</figcaption>
  </figure>
  <p role="status">
    {#await fetchJoke$}
      <div class="spinner-border">
        <span class="visually-hidden">Loading...</span>
      </div>
    {:then jokeText}
      <div class="alert alert-info">Random wisdom: {jokeText}</div>
    {:catch error}
      <div class="alert alert-danger">{error}</div>
    {/await}
  </p>
  <button on:click={() => fetchJoke$ = fetchRandomJoke()} class="btn btn-primary">Refresh</button>
</main>
